name: Test Workflow Validation

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "Checking src structure..."
        ls -la src/
        echo "Checking services structure..."
        ls -la src/services/
        echo "Checking FastAPI structure..."
        ls -la src/services/api-fastapi/ || echo "FastAPI directory not found"
        echo "Checking Docker files..."
        ls -la infra/docker/ || echo "Docker directory not found"
        echo "Checking tests..."
        ls -la tests/ || echo "Tests directory not found"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Test Python imports
      run: |
        python -c "print('Python setup successful')"

    - name: Basic FastAPI test
      run: |
        pip install fastapi uvicorn
        python -c "from fastapi import FastAPI; print('FastAPI import successful')"
